# Generated by Django 4.1.7 on 2023-03-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='c_cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_nombre', models.CharField(max_length=30)),
                ('cliente_apellido', models.CharField(max_length=30)),
                ('cliente_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='c_empleado',
            fields=[
                ('empleado_id', models.AutoField(primary_key=True, serialize=False)),
                ('empleado_nombre', models.CharField(max_length=30)),
                ('empleado_apellido', models.CharField(max_length=30)),
                ('empleado_area', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='c_habitacion',
            fields=[
                ('habitacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('habitacion_tipo', models.CharField(max_length=30)),
                ('habitacion_fecha_reserva', models.DateField()),
                ('habitacion_numero', models.IntegerField()),
            ],
        ),
    ]
