# Generated by Django 4.1.7 on 2023-03-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='c_cliente',
            new_name='modelo_cliente',
        ),
        migrations.RenameModel(
            old_name='c_empleado',
            new_name='modelo_empleado',
        ),
        migrations.RenameModel(
            old_name='c_habitacion',
            new_name='modelo_habitacion',
        ),
    ]
